apiVersion: apps/v1
kind: Deployment
metadata:
  name: internal-api-coll-43eb1edd9d86454a9278edfd33a73710-depl
  labels:
    app: internal-api-coll-43eb1edd9d86454a9278edfd33a73710
    release: prometheus  # Added label for PodMonitor discovery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: internal-api-coll-43eb1edd9d86454a9278edfd33a73710
      release: prometheus  # Added label for PodMonitor discovery
  template:
    metadata:
      labels:
        app: internal-api-coll-43eb1edd9d86454a9278edfd33a73710
        release: prometheus  # Added label for PodMonitor discovery
    spec:
      containers:
        - name: internal-api-coll-43eb1edd9d86454a9278edfd33a73710
          image: 216084506783.dkr.ecr.ap-south-1.amazonaws.com/backstract_apps:internal-api-coll-43eb1edd9d86454a9278edfd33a73710
          imagePullPolicy: Always
          ports:
            - containerPort: 7070
              name: http  # Optional for HTTP traffic
            - containerPort: 7070 #same as the deployed code
              name: metrics  # Added port for metrics scraping